### ISSUE TITLE
TypeError in simple `CorrFitter` example

### ISSUE THREAD

**Issue by erinaldi** [gplepage/corrfitter#1]
Installing `gvar`, `lsqfit` and `corrfitter` from scratch using the latest git versions and python3.5 (from anaconda)

Below is the installation process, which is smooth.

```
gvar: make install
python -m pip install . --user
Processing /Users/enrythebest/Physics/Codes/gvar
Requirement already satisfied: cython>=0.17 in /anaconda/lib/python3.5/site-packages (from gvar==8.2.2)
Requirement already satisfied: numpy>=1.7 in /anaconda/lib/python3.5/site-packages (from gvar==8.2.2)
Installing collected packages: gvar
  Running setup.py install for gvar ... done
Successfully installed gvar-8.2.2
```

```
lsqfit: make install
python -m pip install . --user
Processing /Users/enrythebest/Physics/Codes/lsqfit
Requirement already satisfied: cython>=0.17 in /anaconda/lib/python3.5/site-packages (from lsqfit==9.1.3)
Requirement already satisfied: numpy>=1.7 in /anaconda/lib/python3.5/site-packages (from lsqfit==9.1.3)
Requirement already satisfied: gvar>=8.0 in /Users/enrythebest/.local/lib/python3.5/site-packages (from lsqfit==9.1.3)
Installing collected packages: lsqfit
  Running setup.py install for lsqfit ... done
Successfully installed lsqfit-9.1.3
```

```
corrfitter: make install
python -m pip install . --user
Processing /Users/enrythebest/Physics/Codes/corrfitter
Requirement already satisfied: lsqfit>=9.1.1 in /Users/enrythebest/.local/lib/python3.5/site-packages (from corrfitter==6.0.1)
Requirement already satisfied: gvar>=8.2 in /Users/enrythebest/.local/lib/python3.5/site-packages (from corrfitter==6.0.1)
Requirement already satisfied: numpy>=1.7 in /anaconda/lib/python3.5/site-packages (from corrfitter==6.0.1)
Requirement already satisfied: cython>=0.17 in /anaconda/lib/python3.5/site-packages (from lsqfit>=9.1.1->corrfitter==6.0.1)
Installing collected packages: corrfitter
  Running setup.py install for corrfitter ... done
Successfully installed corrfitter-6.0.1
```

Then we move to the example in the `corrfitter` package and we run `etas.py`

```
examples: python etas.py
============================== nterm = 2
Traceback (most recent call last):
  File "src/gvar/_gvarcore.pyx", line 820, in gvar._gvarcore.GVarFactory.__call__ (src/gvar/_gvarcore.c:15767)
  File "//anaconda/lib/python3.5/site-packages/numpy/core/numeric.py", line 531, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: float() argument must be a string or a number, not 'slice'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "etas.py", line 45, in <module>
    main()
  File "etas.py", line 15, in main
    fit = fitter.lsqfit(data=data, prior=prior, p0=p0)
  File "/Users/enrythebest/.local/lib/python3.5/site-packages/corrfitter.py", line 942, in lsqfit
    data=data, prior=prior, pdata=pdata, p0=p0, mopt=nterm, **kargs
  File "/Users/enrythebest/.local/lib/python3.5/site-packages/lsqfit/_extras.py", line 923, in lsqfit
    extend=mf['extend'], **fitterargs
  File "/Users/enrythebest/.local/lib/python3.5/site-packages/lsqfit/__init__.py", line 513, in __init__
    extend=extend, uncorrelated_data=self.uncorrelated_data,
  File "/Users/enrythebest/.local/lib/python3.5/site-packages/lsqfit/__init__.py", line 1375, in _unpack_data
    prior = _unpack_gvars(prior)
  File "/Users/enrythebest/.local/lib/python3.5/site-packages/lsqfit/__init__.py", line 1432, in _unpack_gvars
    g = _gvar.gvar(g)
  File "src/gvar/_gvarcore.pyx", line 917, in gvar._gvarcore.GVarFactory.__call__ (src/gvar/_gvarcore.c:18708)
  File "src/gvar/_gvarcore.pyx", line 934, in gvar._gvarcore.GVarFactory.__call__ (src/gvar/_gvarcore.c:19366)
  File "src/gvar/_gvarcore.pyx", line 938, in gvar._gvarcore.GVarFactory.__call__ (src/gvar/_gvarcore.c:19573)
  File "src/gvar/_gvarcore.pyx", line 823, in gvar._gvarcore.GVarFactory.__call__ (src/gvar/_gvarcore.c:15919)
TypeError: Arguments must be numbers or arrays of numbers
```

The error is not present when using older versions of all the packages involved (`gvar`, `lsqfit` and `corrfitter`)

Hints:
- new versions give
```
BufferDict([('ps', BUFFERDICTDATA(slice=slice(0, 64, None), shape=(64,)))])
```
- old versions give
```
BufferDict([('ps',
             array([13726.5(6.1), ...,11364.7(6.5)], dtype=object))])
```
- the error message mentions a problem with a `slice()` object

**Comment by gplepage** [comment]
I believe this a problem caused by the gvar module. I just posted an update to gvar --- version 8.2.3. Updating to that version should make corrfitter work again.

Thanks for posting the problem.

**Comment by erinaldi** [comment]
Thank you. After updating `gvar` to the 8.2.3 version, the error above is gone and the data structure of the `BufferDict` object report above is consistent between the latest and the older versions of `corrfitter`.
